# Generated by Django 5.0.4 on 2026-05-04 07:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ABHAConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('abha_id', models.CharField(db_index=True, max_length=14)),
                ('abha_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('consent_token_enc', models.TextField()),
                ('linked_at', models.DateTimeField()),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='abha_connection', to='clinical.patient')),
            ],
            options={
                'db_table': 'abha_connections',
            },
        ),
        migrations.CreateModel(
            name='ABHAImportLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('record_type', models.CharField(max_length=50)),
                ('raw_fhir_payload', models.JSONField()),
                ('import_status', models.CharField(choices=[('IMPORTED', 'Imported'), ('DUPLICATE', 'Duplicate'), ('REJECTED', 'Rejected')], max_length=15)),
                ('source_hospital', models.CharField(blank=True, max_length=200, null=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_logs', to='abha.abhaconnection')),
                ('created_prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abha_import', to='clinical.prescription')),
            ],
            options={
                'db_table': 'abha_import_logs',
            },
        ),
    ]
