# Generated by Django 5.0.4 on 2026-05-03 16:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caregiver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_professional', models.BooleanField(default=False)),
                ('specialty', models.CharField(blank=True, max_length=200, null=True)),
                ('license_number', models.CharField(blank=True, max_length=100, null=True)),
                ('organization_name', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'clinical_caregivers',
            },
        ),
        migrations.CreateModel(
            name='DrugInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('severity', models.CharField(choices=[('MILD', 'Mild'), ('MODERATE', 'Moderate'), ('SEVERE', 'Severe'), ('CONTRAINDICATED', 'Contraindicated')], max_length=20)),
                ('description', models.TextField()),
                ('source', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'clinical_drug_interactions',
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(db_index=True, max_length=300)),
                ('generic_name', models.CharField(blank=True, max_length=300, null=True)),
                ('brand_name', models.CharField(blank=True, max_length=300, null=True)),
                ('drug_class', models.CharField(blank=True, max_length=200, null=True)),
                ('form', models.CharField(choices=[('TABLET', 'Tablet'), ('CAPSULE', 'Capsule'), ('SYRUP', 'Syrup'), ('INJECTION', 'Injection'), ('DROPS', 'Drops'), ('INHALER', 'Inhaler'), ('PATCH', 'Patch'), ('CREAM', 'Cream'), ('GEL', 'Gel'), ('POWDER', 'Powder'), ('OTHER', 'Other')], default='TABLET', max_length=20)),
                ('default_unit', models.CharField(default='mg', max_length=30)),
                ('strength', models.CharField(blank=True, max_length=50, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=300, null=True)),
                ('requires_food', models.BooleanField(default=False)),
                ('refrigeration_required', models.BooleanField(default=False)),
                ('is_controlled_substance', models.BooleanField(default=False)),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('side_effects', models.TextField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'clinical_medications',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MedicationSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('frequency_type', models.CharField(choices=[('DAILY', 'Every Day'), ('SPECIFIC_DAYS', 'Specific Days of Week'), ('EVERY_N_DAYS', 'Every N Days'), ('AS_NEEDED', 'As Needed (PRN)'), ('ONCE', 'One Time Only'), ('CYCLE', 'Cyclical (e.g. 21 on / 7 off)')], default='DAILY', max_length=20)),
                ('times_of_day', models.JSONField(default=list)),
                ('days_of_week', models.JSONField(default=list)),
                ('interval_days', models.SmallIntegerField(default=1)),
                ('cycle_on_days', models.SmallIntegerField(blank=True, null=True)),
                ('cycle_off_days', models.SmallIntegerField(blank=True, null=True)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('lead_minutes', models.SmallIntegerField(default=5)),
            ],
            options={
                'db_table': 'clinical_medication_schedules',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('patient_code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('NS', 'Not Specified')], default='NS', max_length=10)),
                ('blood_group', models.CharField(blank=True, max_length=5, null=True)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=100)),
                ('primary_language', models.CharField(default='en', max_length=10)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('is_hospitalized', models.BooleanField(default=False)),
                ('hospitalized_since', models.DateTimeField(blank=True, null=True)),
                ('discharge_expected_at', models.DateTimeField(blank=True, null=True)),
                ('hospital_name', models.CharField(blank=True, max_length=300, null=True)),
                ('cognitive_status', models.CharField(choices=[('NORMAL', 'Normal'), ('MILD', 'Mild Impairment'), ('MODERATE', 'Moderate Impairment'), ('SEVERE', 'Severe Impairment')], default='NORMAL', max_length=20)),
                ('has_vision_impairment', models.BooleanField(default=False)),
                ('has_hearing_impairment', models.BooleanField(default=False)),
                ('requires_assistance', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'clinical_patients',
            },
        ),
        migrations.CreateModel(
            name='PatientCaregiverLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('permission_level', models.CharField(choices=[('view_only', 'View Only'), ('log_doses', 'Log Doses'), ('manage_schedule', 'Manage Schedule'), ('full_access', 'Full Access')], default='view_only', max_length=30)),
                ('can_receive_alerts', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=False)),
                ('invite_token', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('invite_expires_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'clinical_caregiver_links',
            },
        ),
        migrations.CreateModel(
            name='PatientCondition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('icd10_code', models.CharField(blank=True, max_length=10, null=True)),
                ('condition_name', models.CharField(max_length=300)),
                ('severity', models.CharField(choices=[('MILD', 'Mild'), ('MODERATE', 'Moderate'), ('SEVERE', 'Severe')], default='MILD', max_length=20)),
                ('diagnosed_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'clinical_patient_conditions',
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('prescribed_by', models.CharField(blank=True, max_length=300, null=True)),
                ('prescribing_doctor_id', models.UUIDField(blank=True, null=True)),
                ('dosage_value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('dosage_unit', models.CharField(default='mg', max_length=30)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_indefinite', models.BooleanField(default=False)),
                ('refill_alert_days', models.SmallIntegerField(default=7)),
                ('total_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('remaining_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('purpose', models.CharField(blank=True, max_length=500, null=True)),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'clinical_prescriptions',
                'ordering': ['-created_at'],
            },
        ),
    ]
