# Generated by Django 5.0.4 on 2026-05-03 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='caregiver',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caregiver_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='druginteraction',
            name='medication_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_a', to='clinical.medication'),
        ),
        migrations.AddField(
            model_name='druginteraction',
            name='medication_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_b', to='clinical.medication'),
        ),
        migrations.AddField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientcaregiverlink',
            name='caregiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_links', to='clinical.caregiver'),
        ),
        migrations.AddField(
            model_name='patientcaregiverlink',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caregiver_links', to='clinical.patient'),
        ),
        migrations.AddField(
            model_name='patientcondition',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='clinical.patient'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='clinical.medication'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='clinical.patient'),
        ),
        migrations.AddField(
            model_name='medicationschedule',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='clinical.prescription'),
        ),
        migrations.AlterUniqueTogether(
            name='druginteraction',
            unique_together={('medication_a', 'medication_b')},
        ),
        migrations.AlterUniqueTogether(
            name='patientcaregiverlink',
            unique_together={('patient', 'caregiver')},
        ),
    ]
