# Generated by Django 5.0.4 on 2026-05-04 09:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugInteractionCheckLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('prescription_id', models.UUIDField(blank=True, null=True)),
                ('medications_checked', models.JSONField(default=list)),
                ('interactions_found', models.JSONField(default=list)),
                ('has_severe', models.BooleanField(default=False)),
                ('api_source', models.CharField(default='OPENFDA', max_length=50)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interaction_logs', to='clinical.patient')),
            ],
            options={
                'db_table': 'clinical_interaction_check_logs',
            },
        ),
    ]
