# Generated by Django 5.0.4 on 2026-05-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0003_druginteractionchecklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_travel_mode',
            field=models.BooleanField(default=False, help_text='If True, IoT device is ignored and scheduling relies entirely on the app.'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='compartment_number',
            field=models.SmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='current_pill_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of pills currently inside the mapped compartment'),
        ),
    ]
