# Generated by Django 5.0.4 on 2026-05-04 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor_portal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctorpatientlink',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_links', to='doctor_portal.doctorprofile'),
        ),
        migrations.AddField(
            model_name='digitalprescription',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='digital_prescriptions', to='doctor_portal.doctorprofile'),
        ),
        migrations.AddIndex(
            model_name='doctorpatientlink',
            index=models.Index(fields=['patient', 'can_receive_alerts'], name='doctor_pati_patient_9ddf48_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='doctorpatientlink',
            unique_together={('doctor', 'patient')},
        ),
        migrations.AddIndex(
            model_name='digitalprescription',
            index=models.Index(fields=['patient', 'is_accepted'], name='doctor_digi_patient_ada89d_idx'),
        ),
    ]
