# Generated by Django 5.0.4 on 2026-05-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_portal', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalprescription',
            name='compartment_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='digitalprescription',
            name='current_pill_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
