# Generated by Django 5.0.4 on 2026-05-23 04:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_id', models.CharField(db_index=True, max_length=30, unique=True)),
                ('patient_name', models.CharField(default='Unknown', max_length=150)),
                ('patient_age', models.PositiveIntegerField(blank=True, null=True)),
                ('patient_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('patient_gender', models.CharField(blank=True, max_length=10, null=True)),
                ('patient_lat', models.FloatField(blank=True, null=True)),
                ('patient_lng', models.FloatField(blank=True, null=True)),
                ('raw_symptoms_text', models.TextField()),
                ('known_conditions', models.TextField(blank=True, null=True)),
                ('ai_p_level', models.CharField(blank=True, choices=[('P1', 'P1 — Critical'), ('P2', 'P2 — Urgent'), ('P3', 'P3 — Moderate'), ('P4', 'P4 — Low')], max_length=5, null=True)),
                ('ai_severity_label', models.CharField(blank=True, max_length=30, null=True)),
                ('ai_doctor_category', models.CharField(blank=True, max_length=100, null=True)),
                ('ai_confidence', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=10)),
                ('ai_reasoning', models.TextField(blank=True, null=True)),
                ('ai_red_flags', models.JSONField(default=list)),
                ('ai_possible_conditions', models.JSONField(default=list)),
                ('ai_requires_ambulance', models.BooleanField(default=False)),
                ('ai_requires_icu', models.BooleanField(default=False)),
                ('ai_was_escalated', models.BooleanField(default=False)),
                ('needs_profile', models.JSONField(blank=True, null=True)),
                ('recommended_hospitals', models.JSONField(default=list)),
                ('routing_explanation', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('INCOMING', 'Incoming'), ('DISPATCHED', 'Dispatched'), ('RESOLVED', 'Resolved'), ('FLAGGED_FOR_REVIEW', 'Flagged for Review'), ('CANCELLED', 'Cancelled')], default='INCOMING', max_length=25)),
                ('actual_p_level', models.CharField(blank=True, choices=[('P1', 'P1 — Critical'), ('P2', 'P2 — Urgent'), ('P3', 'P3 — Moderate'), ('P4', 'P4 — Low')], max_length=5, null=True)),
                ('outcome_notes', models.TextField(blank=True, null=True)),
                ('was_undertriaged', models.BooleanField(blank=True, null=True)),
                ('was_overtriaged', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_cases', to=settings.AUTH_USER_MODEL)),
                ('top_hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='top_recommended_cases', to='hospitals.hospital')),
            ],
            options={
                'db_table': 'emergency_cases',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='emergency_c_status_69d904_idx'), models.Index(fields=['ai_p_level'], name='emergency_c_ai_p_le_c318ff_idx'), models.Index(fields=['created_at'], name='emergency_c_created_dbde79_idx'), models.Index(fields=['was_undertriaged'], name='emergency_c_was_und_1dd066_idx')],
            },
        ),
    ]
