"""Quick WebSocket test — reads tokens from _ws_tokens.json (generated by manage.py shell)."""
import asyncio, json, sys
from pathlib import Path

try:
    import websockets
except ImportError:
    print("ERROR: pip install websockets")
    sys.exit(1)

data    = json.loads(Path("_ws_tokens.json").read_text())
PT      = data["pt"]
CT      = data["ct"]
ROOM_ID = data["room"]
WS_BASE = "ws://127.0.0.1:8000"

ok   = lambda m: print(f"  \033[92m✓\033[0m  {m}")
fail = lambda m: print(f"  \033[91m✗\033[0m  {m}")
info = lambda m: print(f"  ›   {m}")

results = {}


async def patient_flow(ws):
    # 1. receive history
    raw   = await asyncio.wait_for(ws.recv(), timeout=6)
    frame = json.loads(raw)
    assert frame["type"] == "history", f"expected history, got {frame['type']}"
    ok(f"Patient — history received ({len(frame['messages'])} stored msgs)")

    # 2. send a message
    await ws.send(json.dumps({"type": "message", "content": "Hello from patient!"}))
    ok("Patient — sent: 'Hello from patient!'")

    # 3. wait for caregiver's reply (skip own message echo)
    deadline = asyncio.get_event_loop().time() + 10
    while asyncio.get_event_loop().time() < deadline:
        try:
            raw = await asyncio.wait_for(ws.recv(), timeout=2)
        except asyncio.TimeoutError:
            continue
        f = json.loads(raw)
        if f.get("type") == "message" and not f.get("is_own"):
            ok(f"Patient — received reply: '{f['content']}'")
            results["patient_got_reply"] = True
            return
    results["patient_got_reply"] = False
    fail("Patient — did not receive caregiver reply within 10s")


async def caregiver_flow(ws):
    # 1. receive history
    raw   = await asyncio.wait_for(ws.recv(), timeout=6)
    frame = json.loads(raw)
    assert frame["type"] == "history", f"expected history, got {frame['type']}"
    ok(f"Caregiver — history received ({len(frame['messages'])} stored msgs)")

    # 2. wait for patient's message
    deadline = asyncio.get_event_loop().time() + 10
    while asyncio.get_event_loop().time() < deadline:
        try:
            raw = await asyncio.wait_for(ws.recv(), timeout=2)
        except asyncio.TimeoutError:
            continue
        f = json.loads(raw)
        if f.get("type") == "message" and not f.get("is_own"):
            ok(f"Caregiver — received: '{f['content']}'")
            results["caregiver_got_msg"] = True
            # 3. reply
            await ws.send(json.dumps({"type": "message", "content": "Hi! Got your message."}))
            ok("Caregiver — replied: 'Hi! Got your message.'")
            return
    results["caregiver_got_msg"] = False
    fail("Caregiver — did not receive patient message within 10s")


async def typing_test():
    """Quick typing indicator check."""
    pu = f"{WS_BASE}/ws/chat/{ROOM_ID}/?token={PT}"
    cu = f"{WS_BASE}/ws/chat/{ROOM_ID}/?token={CT}"
    got = {"typing": False}

    async def p(ws):
        await asyncio.wait_for(ws.recv(), timeout=6)   # history
        await ws.send(json.dumps({"type": "typing", "is_typing": True}))

    async def c(ws):
        await asyncio.wait_for(ws.recv(), timeout=6)   # history
        deadline = asyncio.get_event_loop().time() + 5
        while asyncio.get_event_loop().time() < deadline:
            try:
                raw = await asyncio.wait_for(ws.recv(), timeout=2)
            except asyncio.TimeoutError:
                continue
            f = json.loads(raw)
            if f.get("type") == "typing":
                got["typing"] = True
                return

    async with websockets.connect(pu) as pw, websockets.connect(cu) as cw:
        await asyncio.gather(p(pw), c(cw))

    if got["typing"]:
        ok("Typing indicator — caregiver received patient's typing event")
    else:
        info("Typing indicator — not received (non-fatal; channel layer may be InMemory single-process)")


async def main():
    print()
    print("\033[1m=== MedAdhere WebSocket Test ===\033[0m")
    print()
    info(f"Room ID : {ROOM_ID}")
    info(f"Patient : patient+clinic-demo@medadhere.test")
    info(f"Caregiver: caregiver@medadhere.test")
    print()

    pu = f"{WS_BASE}/ws/chat/{ROOM_ID}/?token={PT}"
    cu = f"{WS_BASE}/ws/chat/{ROOM_ID}/?token={CT}"

    print("\033[1mStep 1 — Connect both users\033[0m")
    try:
        async with websockets.connect(pu) as pw, websockets.connect(cu) as cw:
            ok("Both WebSocket connections established (101 Switching Protocols)")
            print()
            print("\033[1mStep 2 — Message exchange\033[0m")
            await asyncio.gather(patient_flow(pw), caregiver_flow(cw))
    except Exception as e:
        fail(f"Connection failed: {e}")
        sys.exit(1)

    print()
    print("\033[1mStep 3 — Typing indicator\033[0m")
    try:
        await typing_test()
    except Exception as e:
        info(f"Typing test skipped: {e}")

    print()
    print("\033[1m─── RESULTS ───\033[0m")
    if results.get("caregiver_got_msg") and results.get("patient_got_reply"):
        print("\n  \033[92m\033[1mALL TESTS PASSED\033[0m")
        print("  WebSocket works ✓  patient→caregiver ✓  caregiver→patient ✓\n")
    else:
        print("\n  \033[91m\033[1mFAILED\033[0m")
        sys.exit(1)


asyncio.run(main())
