# Generated by Django 5.0.4 on 2026-05-04 07:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('notification_type', models.CharField(choices=[('DOSE_REMINDER', 'Dose Reminder'), ('MISSED_DOSE_ALERT', 'Missed Dose Alert'), ('CAREGIVER_ALERT', 'Caregiver Alert'), ('REFILL_ALERT', 'Refill Alert'), ('PRESCRIPTION_EXPIRY', 'Prescription Expiry'), ('SUBSCRIPTION_EXPIRY', 'Subscription Expiry'), ('ANOMALY_ALERT', 'Anomaly Alert'), ('CAREGIVER_INVITE', 'Caregiver Invite'), ('SYSTEM', 'System Notification'), ('WELCOME', 'Welcome')], max_length=40, unique=True)),
                ('channel', models.CharField(choices=[('PUSH', 'Push Notification (FCM/APNs)'), ('EMAIL', 'Email'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp'), ('VOICE', 'Voice Call'), ('IN_APP', 'In-App')], max_length=20)),
                ('language', models.CharField(default='en', max_length=10)),
                ('subject_template', models.CharField(blank=True, max_length=500)),
                ('body_template', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'notifications_templates',
                'unique_together': {('notification_type', 'channel', 'language')},
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('notification_type', models.CharField(choices=[('DOSE_REMINDER', 'Dose Reminder'), ('MISSED_DOSE_ALERT', 'Missed Dose Alert'), ('CAREGIVER_ALERT', 'Caregiver Alert'), ('REFILL_ALERT', 'Refill Alert'), ('PRESCRIPTION_EXPIRY', 'Prescription Expiry'), ('SUBSCRIPTION_EXPIRY', 'Subscription Expiry'), ('ANOMALY_ALERT', 'Anomaly Alert'), ('CAREGIVER_INVITE', 'Caregiver Invite'), ('SYSTEM', 'System Notification'), ('WELCOME', 'Welcome')], max_length=40)),
                ('channel', models.CharField(choices=[('PUSH', 'Push Notification (FCM/APNs)'), ('EMAIL', 'Email'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp'), ('VOICE', 'Voice Call'), ('IN_APP', 'In-App')], default='IN_APP', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('READ', 'Read'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('data', models.JSONField(default=dict)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('failed_reason', models.TextField(blank=True, null=True)),
                ('external_id', models.CharField(blank=True, max_length=300, null=True)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status', '-created_at'], name='notificatio_user_id_15a58a_idx'), models.Index(fields=['user', 'read_at'], name='notificatio_user_id_aa6751_idx')],
            },
        ),
    ]
