# Generated by Django 5.0.4 on 2026-05-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_add_account_security_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('DOSE_REMINDER', 'Dose Reminder'), ('MISSED_DOSE_ALERT', 'Missed Dose Alert'), ('CAREGIVER_ALERT', 'Caregiver Alert'), ('REFILL_ALERT', 'Refill Alert'), ('PRESCRIPTION_EXPIRY', 'Prescription Expiry'), ('SUBSCRIPTION_EXPIRY', 'Subscription Expiry'), ('ANOMALY_ALERT', 'Anomaly Alert'), ('CAREGIVER_INVITE', 'Caregiver Invite'), ('SYSTEM', 'System Notification'), ('WELCOME', 'Welcome'), ('ACCOUNT_SECURITY', 'Account Security'), ('GEOFENCE_EXIT', 'Geofence Exit Alert')], max_length=40),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='notification_type',
            field=models.CharField(choices=[('DOSE_REMINDER', 'Dose Reminder'), ('MISSED_DOSE_ALERT', 'Missed Dose Alert'), ('CAREGIVER_ALERT', 'Caregiver Alert'), ('REFILL_ALERT', 'Refill Alert'), ('PRESCRIPTION_EXPIRY', 'Prescription Expiry'), ('SUBSCRIPTION_EXPIRY', 'Subscription Expiry'), ('ANOMALY_ALERT', 'Anomaly Alert'), ('CAREGIVER_INVITE', 'Caregiver Invite'), ('SYSTEM', 'System Notification'), ('WELCOME', 'Welcome'), ('ACCOUNT_SECURITY', 'Account Security'), ('GEOFENCE_EXIT', 'Geofence Exit Alert')], max_length=40, unique=True),
        ),
    ]
