# Generated by Django 5.0.4 on 2026-05-03 16:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical', '0002_initial'),
        ('telemetry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('device_name', models.CharField(max_length=200)),
                ('device_type', models.CharField(choices=[('PILLBOX', 'Smart Pillbox'), ('WEARABLE', 'Wearable'), ('MONITOR', 'Vital Monitor'), ('OTHER', 'Other')], default='PILLBOX', max_length=30)),
                ('api_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('battery_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('firmware_version', models.CharField(blank=True, max_length=50)),
                ('linked_patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smart_devices', to='clinical.patient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smart_devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceCompartmentMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('compartment_number', models.PositiveSmallIntegerField()),
                ('next_scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compartments', to='iot.device')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iot_compartments', to='clinical.prescription')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('event_uuid', models.UUIDField(db_index=True, unique=True)),
                ('event_type', models.CharField(choices=[('DOSE_TAKEN', 'Dose Taken'), ('DOSE_MISSED', 'Dose Missed'), ('COMPARTMENT_OPEN', 'Compartment Opened'), ('LOW_BATTERY', 'Low Battery'), ('TAMPER', 'Tamper Detected'), ('DEVICE_ON', 'Device Powered On'), ('DEVICE_OFF', 'Device Powered Off')], max_length=30)),
                ('compartment_num', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('raw_payload', models.JSONField(default=dict)),
                ('processed', models.BooleanField(default=False)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='iot.device')),
                ('telemetry_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iot_device_events', to='telemetry.telemetryevent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceHeartbeat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('battery_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('firmware_version', models.CharField(blank=True, max_length=50)),
                ('wifi_strength', models.IntegerField(blank=True, null=True)),
                ('uptime_seconds', models.PositiveIntegerField(default=0)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heartbeats', to='iot.device')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['api_key'], name='idx_iot_device_api_key'),
        ),
        migrations.AlterUniqueTogether(
            name='devicecompartmentmapping',
            unique_together={('device', 'compartment_number')},
        ),
    ]
