# Generated by Django 5.0.4 on 2026-05-10 14:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0004_add_version_to_dispenser_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicecompartmentmapping',
            options={'ordering': ['compartment_number']},
        ),
        migrations.AddField(
            model_name='device',
            name='caregiver_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='device',
            name='caregiver_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='device',
            name='caregiver_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='device',
            name='chemist_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='device',
            name='chemist_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='device',
            name='fill_mode_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='device',
            name='fill_mode_compartment',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicecompartmentmapping',
            name='is_filled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='devicecompartmentmapping',
            name='last_dose_prepared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicecompartmentmapping',
            name='last_filled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicecompartmentmapping',
            name='meal_dependency',
            field=models.CharField(choices=[('NONE', 'No Dependency'), ('BEFORE_BREAKFAST', 'Before Breakfast'), ('AFTER_BREAKFAST', 'After Breakfast'), ('BEFORE_LUNCH', 'Before Lunch'), ('AFTER_LUNCH', 'After Lunch'), ('BEFORE_DINNER', 'Before Dinner'), ('AFTER_DINNER', 'After Dinner')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='devicecompartmentmapping',
            name='medication_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='devicecompartmentmapping',
            name='missed_dose_alert_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='devicecompartmentmapping',
            name='pills_remaining',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='devicecompartmentmapping',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'High Priority'), ('NORMAL', 'Normal')], default='NORMAL', max_length=10),
        ),
        migrations.AddField(
            model_name='devicecompartmentmapping',
            name='refill_alert_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='devicecompartmentmapping',
            name='total_pills',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='devicecommand',
            name='command_type',
            field=models.CharField(choices=[('SYNC_SCHEDULE', 'Sync Schedule'), ('PREPARE_COMPARTMENT', 'Prepare Compartment'), ('FORCE_OPEN_LID', 'Force Open Lid'), ('START_FILL_MODE', 'Start Fill Mode'), ('NEXT_COMPARTMENT', 'Next Compartment (Fill)'), ('END_FILL_MODE', 'End Fill Mode'), ('RESET_FLAGS', 'Reset Daily Dispense Flags'), ('LOCK_DEVICE', 'Lock Device'), ('UPDATE_DISPLAY', 'Update Display'), ('FIRMWARE_UPDATE', 'Firmware Update'), ('SYNC_TIME', 'Sync Time'), ('GATE_LOCK', 'Lock Gate'), ('GATE_UNLOCK', 'Unlock Gate'), ('OPEN_GATE', 'Open Gate'), ('READ_FILL_WEIGHT', 'Read Fill Weight')], max_length=30),
        ),
        migrations.AlterField(
            model_name='deviceevent',
            name='event_type',
            field=models.CharField(choices=[('DEVICE_BOOT', 'Device Boot'), ('HEARTBEAT', 'Heartbeat'), ('COMPARTMENT_ROTATED', 'Compartment Rotated'), ('HAND_DETECTED', 'Hand Detected'), ('LID_OPENED', 'Lid Opened'), ('LID_CLOSED', 'Lid Closed'), ('DOSE_TAKEN', 'Dose Taken'), ('DOSE_TIMEOUT', 'Dose Timeout (Missed)'), ('DOSE_SKIPPED', 'Dose Skipped'), ('DOSE_DUPLICATE_BLOCKED', 'Duplicate Dose Blocked'), ('COMMAND_ACKNOWLEDGED', 'Command Acknowledged'), ('FILL_STARTED', 'Fill Mode Started'), ('FILL_CONFIRMED', 'Fill Confirmed by User'), ('FILL_COMPLETED', 'Fill Mode Completed'), ('DOSE_MISSED', 'Dose Missed'), ('COMPARTMENT_OPEN', 'Compartment Opened'), ('LOW_BATTERY', 'Low Battery'), ('TAMPER', 'Tamper Detected'), ('DEVICE_ON', 'Device Powered On'), ('DEVICE_OFF', 'Device Powered Off')], max_length=40),
        ),
        migrations.AlterField(
            model_name='dosesession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='dosesession',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='physicalcompartment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='physicalcompartment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='subcompartment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='subcompartment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='MealLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('breakfast_done', models.BooleanField(default=False)),
                ('breakfast_time', models.DateTimeField(blank=True, null=True)),
                ('lunch_done', models.BooleanField(default=False)),
                ('lunch_time', models.DateTimeField(blank=True, null=True)),
                ('dinner_done', models.BooleanField(default=False)),
                ('dinner_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
