# Generated by Django 5.0.4 on 2026-05-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0005_alter_devicecompartmentmapping_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicecommand',
            name='command_type',
            field=models.CharField(choices=[('SYNC_SCHEDULE', 'Sync Schedule'), ('PREPARE_COMPARTMENT', 'Prepare Compartment'), ('FORCE_OPEN_LID', 'Force Open Lid'), ('CANCEL_DISPENSE', 'Cancel Dispense'), ('START_FILL_MODE', 'Start Fill Mode'), ('NEXT_COMPARTMENT', 'Next Compartment (Fill)'), ('END_FILL_MODE', 'End Fill Mode'), ('RESET_FLAGS', 'Reset Daily Dispense Flags'), ('LOCK_DEVICE', 'Lock Device'), ('UPDATE_DISPLAY', 'Update Display'), ('FIRMWARE_UPDATE', 'Firmware Update'), ('SYNC_TIME', 'Sync Time'), ('GATE_LOCK', 'Lock Gate'), ('GATE_UNLOCK', 'Unlock Gate'), ('OPEN_GATE', 'Open Gate'), ('READ_FILL_WEIGHT', 'Read Fill Weight')], max_length=30),
        ),
    ]
