# Generated by Django 5.0.4 on 2026-05-03 16:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('anomaly_type', models.CharField(choices=[('CONSECUTIVE_MISSES', 'Consecutive Missed Doses'), ('VITAL_SPIKE', 'Vital Sign Spike'), ('DEVICE_OFFLINE', 'Device Offline'), ('LOW_REFILL', 'Low Medication Refill'), ('TAMPER', 'Device Tamper')], max_length=30)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='WARNING', max_length=20)),
                ('description', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='clinical.patient')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'telemetry_anomalies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IoTDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('device_type', models.CharField(choices=[('PILL_DISPENSER', 'Smart Pill Dispenser'), ('SMARTWATCH', 'Smartwatch'), ('BP_MONITOR', 'Blood Pressure Monitor'), ('GLUCOSE_METER', 'Glucose Meter'), ('PULSE_OXIMETER', 'Pulse Oximeter'), ('WEIGHT_SCALE', 'Smart Weight Scale'), ('THERMOMETER', 'Smart Thermometer'), ('OTHER', 'Other')], max_length=30)),
                ('device_name', models.CharField(max_length=200)),
                ('hardware_id', models.CharField(db_index=True, max_length=200, unique=True)),
                ('firmware_version', models.CharField(blank=True, max_length=50, null=True)),
                ('api_key_hash', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('battery_level', models.SmallIntegerField(blank=True, null=True)),
                ('signal_strength', models.SmallIntegerField(blank=True, null=True)),
                ('compartments', models.SmallIntegerField(default=7)),
                ('meta', models.JSONField(default=dict)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iot_devices', to='clinical.patient')),
            ],
            options={
                'db_table': 'telemetry_iot_devices',
            },
        ),
        migrations.CreateModel(
            name='TelemetryEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('event_type', models.CharField(choices=[('HEARTBEAT', 'Device Heartbeat'), ('DOOR_OPENED', 'Compartment Door Opened'), ('DOSE_DISPENSED', 'Dose Dispensed'), ('DOSE_NOT_TAKEN', 'Dose Dispensed But Not Taken'), ('BUTTON_PRESS', 'Patient Confirmation Button'), ('LOW_BATTERY', 'Low Battery'), ('MEDICATION_LOADED', 'Medication Reloaded'), ('ALERT_TRIGGERED', 'Device Alert'), ('VITAL_READING', 'Vital Sign Reading'), ('TAMPER', 'Tamper Detected')], max_length=30)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('payload', models.JSONField(default=dict)),
                ('is_processed', models.BooleanField(default=False)),
                ('idempotency_key', models.CharField(db_index=True, max_length=200, unique=True)),
                ('sequence_no', models.BigIntegerField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='telemetry.iotdevice')),
            ],
            options={
                'db_table': 'telemetry_events',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['device', 'occurred_at'], name='telemetry_e_device__a4715f_idx'), models.Index(fields=['is_processed', 'event_type'], name='telemetry_e_is_proc_7cd746_idx')],
            },
        ),
        migrations.CreateModel(
            name='VitalReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('vital_type', models.CharField(choices=[('HEART_RATE', 'Heart Rate (bpm)'), ('BLOOD_PRESSURE', 'Blood Pressure (mmHg)'), ('SPO2', 'Oxygen Saturation (%)'), ('GLUCOSE', 'Blood Glucose (mg/dL)'), ('TEMPERATURE', 'Body Temperature (°C)'), ('WEIGHT', 'Weight (kg)'), ('RESPIRATORY_RATE', 'Respiratory Rate (breaths/min)')], max_length=30)),
                ('value_primary', models.DecimalField(decimal_places=2, max_digits=8)),
                ('value_secondary', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('unit', models.CharField(max_length=20)),
                ('recorded_at', models.DateTimeField(db_index=True)),
                ('source', models.CharField(choices=[('IOT', 'IoT'), ('MANUAL', 'Manual'), ('APP', 'App')], default='IOT', max_length=20)),
                ('is_abnormal', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vital_readings', to='telemetry.iotdevice')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital_readings', to='clinical.patient')),
            ],
            options={
                'db_table': 'telemetry_vital_readings',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['patient', 'vital_type', 'recorded_at'], name='telemetry_v_patient_d30d17_idx')],
            },
        ),
    ]
