# Generated by Django 5.0.4 on 2026-05-04 07:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FHIRConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('fhir_server_url', models.URLField()),
                ('access_token_enc', models.TextField()),
                ('refresh_token_enc', models.TextField(blank=True, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('hospital_name', models.CharField(max_length=200)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('IDLE', 'Idle'), ('SYNCING', 'Syncing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='IDLE', max_length=10)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fhir_connections', to='clinical.patient')),
            ],
            options={
                'db_table': 'fhir_connections',
            },
        ),
        migrations.CreateModel(
            name='FHIRImportLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('resource_type', models.CharField(max_length=50)),
                ('external_id', models.CharField(max_length=200)),
                ('raw_payload', models.JSONField()),
                ('import_status', models.CharField(choices=[('IMPORTED', 'Imported'), ('DUPLICATE', 'Duplicate'), ('REJECTED', 'Rejected')], max_length=15)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_logs', to='fhir_integration.fhirconnection')),
                ('created_prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fhir_import', to='clinical.prescription')),
            ],
            options={
                'db_table': 'fhir_import_logs',
                'unique_together': {('connection', 'external_id')},
            },
        ),
    ]
