# Generated by Django 5.0.4 on 2026-05-04 07:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SideEffectReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('symptom', models.CharField(max_length=200)),
                ('severity', models.CharField(choices=[('MILD', 'Mild'), ('MODERATE', 'Moderate'), ('SEVERE', 'Severe'), ('LIFE_THREATENING', 'Life Threatening')], db_index=True, max_length=20)),
                ('onset_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('is_ongoing', models.BooleanField(default=True)),
                ('reported_to_doctor', models.BooleanField(default=False)),
                ('reported_to_cdsco', models.BooleanField(default=False)),
                ('cdsco_report_id', models.CharField(blank=True, max_length=100, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='side_effect_reports', to='clinical.patient')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='side_effect_reports', to='clinical.prescription')),
            ],
            options={
                'db_table': 'pharmacovig_side_effect_reports',
                'indexes': [models.Index(fields=['prescription', 'severity'], name='pharmacovig_prescri_cea4a2_idx'), models.Index(fields=['reported_to_cdsco', 'severity'], name='pharmacovig_reporte_8bc4a8_idx')],
            },
        ),
    ]
