# Generated by Django 5.0.4 on 2026-05-05 17:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiinsight',
            options={'ordering': ['-generated_at']},
        ),
        migrations.AlterModelOptions(
            name='aimodelregistry',
            options={'ordering': ['-created_at'], 'verbose_name': 'AI Model', 'verbose_name_plural': 'AI Models'},
        ),
        migrations.AlterModelOptions(
            name='airecommendation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='aiinsight',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='aiinsight',
            name='insight_type',
            field=models.CharField(choices=[('PATTERN_DETECTION', 'Pattern Detection'), ('TIMING_OPTIMIZATION', 'Timing Optimization'), ('RISK_WARNING', 'Risk Warning'), ('POSITIVE_REINFORCEMENT', 'Positive Reinforcement'), ('REFILL_REMINDER', 'Refill Reminder'), ('STREAK_UPDATE', 'Streak Update'), ('WEEKEND_PATTERN', 'Weekend Pattern')], max_length=50),
        ),
        migrations.AlterField(
            model_name='aimodelregistry',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='airecommendation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='airecommendation',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='airecommendation',
            name='recommendation_type',
            field=models.CharField(choices=[('RESCHEDULE_DOSE', 'Reschedule Dose'), ('SIMPLIFY_REGIMEN', 'Simplify Regimen'), ('EDUCATION', 'Education'), ('REFILL_REMINDER', 'Refill Reminder'), ('CONTACT_DOCTOR', 'Contact Doctor'), ('CHANGE_CHANNEL', 'Change Notification Channel'), ('MOTIVATIONAL', 'Motivational'), ('CAREGIVER_INVOLVEMENT', 'Caregiver Involvement')], max_length=50),
        ),
        migrations.AlterField(
            model_name='airecommendation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shown', 'Shown'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('snoozed', 'Snoozed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='airecommendation',
            name='target_audience',
            field=models.CharField(choices=[('patient', 'Patient'), ('caregiver', 'Caregiver'), ('nurse', 'Nurse'), ('admin', 'Admin')], default='patient', max_length=20),
        ),
        migrations.AlterField(
            model_name='patientriskscore',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patientriskscore',
            name='risk_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical'), ('unknown', 'Unknown')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='patientriskscore',
            name='risk_trend',
            field=models.CharField(choices=[('improving', 'Improving'), ('worsening', 'Worsening'), ('stable', 'Stable'), ('new_patient', 'New Patient')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patientriskscore',
            name='trigger',
            field=models.CharField(choices=[('DOSE_EVENT', 'Dose Event'), ('NIGHTLY_BATCH', 'Nightly Batch'), ('MANUAL', 'Manual'), ('SCHEDULE_CHANGE', 'Schedule Change')], default='NIGHTLY_BATCH', max_length=30),
        ),
    ]
