# Generated by Django 5.0.4 on 2026-05-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptioninvoice',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
    ]
