# Generated by Django 5.0.4 on 2026-05-04 07:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdherenceReportShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('recipient_type', models.CharField(choices=[('INSURANCE', 'Insurance Company'), ('EMPLOYER', 'Employer'), ('DOCTOR', 'Doctor'), ('SELF', 'Self')], max_length=20)),
                ('recipient_name', models.CharField(max_length=200)),
                ('access_token', models.CharField(db_index=True, default=uuid.uuid4, max_length=100, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('data_scope', models.JSONField(default=dict)),
                ('is_revoked', models.BooleanField(db_index=True, default=False)),
                ('access_count', models.PositiveIntegerField(default=0)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_shares', to='clinical.patient')),
            ],
            options={
                'db_table': 'insurance_report_shares',
            },
        ),
        migrations.CreateModel(
            name='ReportAccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('accessor_ip', models.GenericIPAddressField()),
                ('accessor_ua', models.TextField()),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='insurance_reports.adherencereportshare')),
            ],
            options={
                'db_table': 'insurance_report_access_logs',
            },
        ),
    ]
