# Generated by Django 5.0.4 on 2026-05-04 07:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('phone_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('state', models.CharField(choices=[('IDLE', 'Idle'), ('AWAITING_DOSE_RESPONSE', 'Awaiting Dose Response'), ('ONBOARDING_LANGUAGE', 'Onboarding: Language'), ('ONBOARDING_NAME', 'Onboarding: Name'), ('ONBOARDING_PHONE_VERIFY', 'Onboarding: Phone Verify'), ('MAIN_MENU', 'Main Menu'), ('HELP', 'Help')], default='IDLE', max_length=30)),
                ('state_data', models.JSONField(default=dict)),
                ('last_activity_at', models.DateTimeField()),
                ('onboarding_done', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_session', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'whatsapp_sessions',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppInteractionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('direction', models.CharField(choices=[('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound')], max_length=10)),
                ('message_body', models.TextField()),
                ('intent', models.CharField(blank=True, choices=[('DOSE_YES', 'Dose Taken'), ('DOSE_NO', 'Dose Not Taken'), ('DOSE_SKIP', 'Dose Skipped'), ('HELP', 'Help'), ('STATUS', 'Status Request'), ('UNKNOWN', 'Unknown')], max_length=15, null=True)),
                ('whatsapp_msg_id', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='whatsapp_bot.whatsappsession')),
            ],
            options={
                'db_table': 'whatsapp_interaction_logs',
            },
        ),
        migrations.AddConstraint(
            model_name='whatsappinteractionlog',
            constraint=models.UniqueConstraint(condition=models.Q(('whatsapp_msg_id__isnull', False)), fields=('whatsapp_msg_id',), name='uq_wa_msg_id'),
        ),
    ]
