# Generated by Django 5.0.4 on 2026-05-04 07:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeofenceZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('label', models.CharField(max_length=100)),
                ('zone_type', models.CharField(choices=[('HOME', 'Home'), ('WORK', 'Work'), ('GYM', 'Gym'), ('CUSTOM', 'Custom')], default='CUSTOM', max_length=10)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('radius_meters', models.PositiveIntegerField(default=200)),
                ('is_active', models.BooleanField(default=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geofence_zones', to='clinical.patient')),
            ],
            options={
                'db_table': 'geofence_zones',
            },
        ),
        migrations.CreateModel(
            name='GeofenceEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('event_type', models.CharField(choices=[('EXIT', 'Zone Exit'), ('ENTRY', 'Zone Entry')], max_length=10)),
                ('triggered_at', models.DateTimeField()),
                ('reminders_sent', models.JSONField(default=list)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geofence_events', to='clinical.patient')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='geofence.geofencezone')),
            ],
            options={
                'db_table': 'geofence_events',
            },
        ),
        migrations.AddIndex(
            model_name='geofencezone',
            index=models.Index(fields=['patient', 'is_active'], name='geofence_zo_patient_7b0806_idx'),
        ),
        migrations.AddIndex(
            model_name='geofenceevent',
            index=models.Index(fields=['patient', 'triggered_at'], name='geofence_ev_patient_e795cb_idx'),
        ),
    ]
