# Generated by Django 5.0.4 on 2026-05-16 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0004_patient_is_travel_mode_and_more'),
        ('geofence', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geofenceevent',
            name='reminders_sent',
        ),
        migrations.AddField(
            model_name='geofenceevent',
            name='alert_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='geofenceevent',
            name='call_placed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='geofenceevent',
            name='patient_lat',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='geofenceevent',
            name='patient_lng',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='geofenceevent',
            name='pending_meds',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='geofencezone',
            name='address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='geofencezone',
            name='alert_on_exit_with_pending_dose',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='geofencezone',
            name='set_by_caregiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_zones', to='clinical.caregiver'),
        ),
    ]
