# Generated by Django 5.0.4 on 2026-05-04 07:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VitalReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('vital_type', models.CharField(choices=[('BP_SYSTOLIC', 'Blood Pressure Systolic (mmHg)'), ('BP_DIASTOLIC', 'Blood Pressure Diastolic (mmHg)'), ('GLUCOSE', 'Blood Glucose (mg/dL)'), ('SPO2', 'Oxygen Saturation (%)'), ('WEIGHT', 'Weight (kg)'), ('HEART_RATE', 'Heart Rate (bpm)'), ('TEMPERATURE', 'Body Temperature (°C)'), ('RESPIRATORY', 'Respiratory Rate (breaths/min)')], db_index=True, max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unit', models.CharField(max_length=20)),
                ('recorded_at', models.DateTimeField(db_index=True)),
                ('source', models.CharField(choices=[('MANUAL', 'Manual Entry'), ('DEVICE', 'IoT Device'), ('HEALTHKIT', 'Apple HealthKit'), ('GOOGLEFIT', 'Google Fit')], default='MANUAL', max_length=15)),
                ('device_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals_readings', to='clinical.patient')),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vital_readings', to='clinical.prescription')),
            ],
            options={
                'db_table': 'vitals_readings',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['patient', 'vital_type', 'recorded_at'], name='vitals_read_patient_3b3469_idx')],
            },
        ),
        migrations.CreateModel(
            name='VitalTarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('vital_type', models.CharField(choices=[('BP_SYSTOLIC', 'Blood Pressure Systolic (mmHg)'), ('BP_DIASTOLIC', 'Blood Pressure Diastolic (mmHg)'), ('GLUCOSE', 'Blood Glucose (mg/dL)'), ('SPO2', 'Oxygen Saturation (%)'), ('WEIGHT', 'Weight (kg)'), ('HEART_RATE', 'Heart Rate (bpm)'), ('TEMPERATURE', 'Body Temperature (°C)'), ('RESPIRATORY', 'Respiratory Rate (breaths/min)')], max_length=20)),
                ('target_min', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('target_max', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('set_by_doctor', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital_targets', to='clinical.patient')),
                ('set_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vitals_targets',
                'unique_together': {('patient', 'vital_type')},
            },
        ),
    ]
