# Generated by Django 5.0.4 on 2026-05-04 07:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Streak',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('current_days', models.PositiveIntegerField(default=0)),
                ('longest_days', models.PositiveIntegerField(default=0)),
                ('last_dose_date', models.DateField(blank=True, null=True)),
                ('last_broken_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to='clinical.patient')),
            ],
            options={
                'db_table': 'gamification_streaks',
            },
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('badge_type', models.CharField(choices=[('FIRST_DOSE', 'First Dose Taken'), ('7_DAY_STREAK', '7-Day Streak'), ('14_DAY_STREAK', '14-Day Streak'), ('30_DAY_STREAK', '30-Day Streak'), ('60_DAY_STREAK', '60-Day Streak'), ('90_DAY_STREAK', '90-Day Streak'), ('180_DAY_STREAK', '180-Day Streak'), ('365_DAY_STREAK', '365-Day Streak'), ('PERFECT_WEEK', 'Perfect Week'), ('PERFECT_MONTH', 'Perfect Month'), ('DEVICE_LINKED', 'Device Linked'), ('ABHA_LINKED', 'ABHA Linked'), ('DIGITAL_RX', 'Digital Prescription'), ('REFILL_PROACTIVE', 'Proactive Refill'), ('CAREGIVER_HERO', 'Caregiver Hero'), ('WHATSAPP_ONBOARDED', 'WhatsApp Onboarded')], max_length=30)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='clinical.patient')),
            ],
            options={
                'db_table': 'gamification_badges',
                'unique_together': {('patient', 'badge_type')},
            },
        ),
        migrations.CreateModel(
            name='WeeklyAdherenceScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('week_start', models.DateField()),
                ('score', models.PositiveIntegerField()),
                ('total_doses', models.PositiveIntegerField()),
                ('taken_doses', models.PositiveIntegerField()),
                ('missed_doses', models.PositiveIntegerField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_scores', to='clinical.patient')),
            ],
            options={
                'db_table': 'gamification_weekly_scores',
                'indexes': [models.Index(fields=['patient', '-week_start'], name='gamificatio_patient_4ecb91_idx')],
                'unique_together': {('patient', 'week_start')},
            },
        ),
    ]
