# Generated by Django 5.0.4 on 2026-05-04 07:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=200)),
                ('subdomain', models.SlugField(unique=True)),
                ('plan', models.CharField(choices=[('CLINIC', 'Clinic'), ('HOSPITAL', 'Hospital'), ('ENTERPRISE', 'Enterprise')], default='CLINIC', max_length=15)),
                ('max_patients', models.PositiveIntegerField(default=500)),
                ('is_active', models.BooleanField(default=True)),
                ('schema_name', models.CharField(blank=True, max_length=63, null=True)),
            ],
            options={
                'db_table': 'tenants',
            },
        ),
        migrations.CreateModel(
            name='TenantAdmin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_primary', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenant_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tenant_admins',
                'unique_together': {('tenant', 'user')},
            },
        ),
    ]
