# Generated by Django 5.0.4 on 2026-05-04 07:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyPartner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('api_base_url', models.URLField()),
                ('api_key_enc', models.TextField()),
                ('webhook_secret', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('supported_states', models.JSONField(default=list)),
                ('avg_delivery_hrs', models.PositiveIntegerField(default=48)),
            ],
            options={
                'db_table': 'pharmacy_partners',
            },
        ),
        migrations.CreateModel(
            name='PharmacyIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('delivery_address', models.JSONField(default=dict)),
                ('saved_payment_method', models.CharField(blank=True, max_length=200, null=True)),
                ('auto_refill_enabled', models.BooleanField(default=False)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pharmacy_integration', to='clinical.patient')),
                ('preferred_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.pharmacypartner')),
            ],
            options={
                'db_table': 'pharmacy_integrations',
            },
        ),
        migrations.CreateModel(
            name='RefillOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('quantity_ordered', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTNER_CONFIRMED', 'Partner Confirmed'), ('DISPATCHED', 'Dispatched'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('partner_order_id', models.CharField(blank=True, max_length=200, null=True)),
                ('estimated_delivery', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('auto_triggered', models.BooleanField(default=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pharmacy.pharmacypartner')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refill_orders', to='clinical.patient')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refill_orders', to='clinical.prescription')),
            ],
            options={
                'db_table': 'pharmacy_refill_orders',
                'indexes': [models.Index(fields=['prescription', 'status'], name='pharmacy_re_prescri_6342ec_idx')],
            },
        ),
    ]
