# Generated by Django 5.0.4 on 2026-05-04 07:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('scheduled_at', models.DateTimeField(db_index=True)),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('TAKEN', 'Taken'), ('MISSED', 'Missed'), ('SKIPPED', 'Skipped'), ('SNOOZED', 'Snoozed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('dose_value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('dose_unit', models.CharField(default='mg', max_length=30)),
                ('with_food', models.BooleanField(default=False)),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('snooze_until', models.DateTimeField(blank=True, null=True)),
                ('snooze_count', models.SmallIntegerField(default=0)),
                ('notification_id', models.CharField(blank=True, max_length=200, null=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_jobs', to='clinical.medicationschedule')),
            ],
            options={
                'db_table': 'scheduling_reminder_jobs',
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='DoseLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('TAKEN', 'Taken'), ('MISSED', 'Missed'), ('SKIPPED', 'Skipped'), ('SNOOZED', 'Snoozed'), ('CANCELLED', 'Cancelled')], max_length=20)),
                ('source', models.CharField(choices=[('APP', 'Mobile / Web App'), ('IOT', 'IoT Pill Dispenser'), ('CAREGIVER', 'Caregiver'), ('VOICE', 'Voice Assistant'), ('NFC', 'NFC Tap')], default='APP', max_length=20)),
                ('taken_at', models.DateTimeField(blank=True, null=True)),
                ('dose_value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('dose_unit', models.CharField(default='mg', max_length=30)),
                ('with_food', models.BooleanField(default=False)),
                ('side_effects', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('mood_score', models.SmallIntegerField(blank=True, null=True)),
                ('pain_score', models.SmallIntegerField(blank=True, null=True)),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('iot_device_id', models.CharField(blank=True, max_length=200, null=True)),
                ('logged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dose_logs_created', to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dose_logs', to='clinical.prescription')),
                ('reminder_job', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dose_log', to='scheduling.reminderjob')),
            ],
            options={
                'db_table': 'scheduling_dose_logs',
                'ordering': ['-taken_at'],
            },
        ),
        migrations.CreateModel(
            name='AdherenceSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=10)),
                ('scheduled_count', models.PositiveIntegerField(default=0)),
                ('taken_count', models.PositiveIntegerField(default=0)),
                ('missed_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('adherence_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adherence_summaries', to='clinical.patient')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adherence_summaries', to='clinical.prescription')),
            ],
            options={
                'db_table': 'scheduling_adherence_summaries',
                'ordering': ['-period_start'],
                'unique_together': {('patient', 'prescription', 'period_start', 'period_type')},
            },
        ),
        migrations.AddIndex(
            model_name='reminderjob',
            index=models.Index(fields=['status', 'scheduled_at'], name='scheduling__status_f3dbe3_idx'),
        ),
        migrations.AddIndex(
            model_name='reminderjob',
            index=models.Index(fields=['schedule', 'scheduled_at'], name='scheduling__schedul_776aa8_idx'),
        ),
        migrations.AddIndex(
            model_name='doselog',
            index=models.Index(fields=['prescription', 'taken_at'], name='scheduling__prescri_2b7e1f_idx'),
        ),
        migrations.AddIndex(
            model_name='doselog',
            index=models.Index(fields=['status', 'taken_at'], name='scheduling__status_3bbac8_idx'),
        ),
    ]
