# Generated by Django 5.0.4 on 2026-05-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PATIENT', 'Patient'), ('DOCTOR', 'Doctor'), ('CAREGIVER', 'Caregiver'), ('NURSE', 'Nurse'), ('PHARMACIST', 'Pharmacist'), ('ADMIN', 'Admin'), ('SUPER_ADMIN', 'Super Admin')], default='PATIENT', max_length=20),
        ),
    ]
